modLoader="javafml"
loaderVersion="[47,)"

license="LGPL-2.1-or-later"
issueTrackerURL=""
showAsResourcePack=false

[[mods]]
  modId="fallen_gems_affixes"
  version="${mcVersion}-${version}"
  displayName="Fallen Gems & Affixes"
  updateJSONURL="https://github.com/KiraKayn/Fallen-Gems-Affixes"
  displayURL="https://github.com/KiraKayn/Fallen-Gems-Affixes"
  logoFile="logo.png"
  credits="me"
  authors="Kayn"
  description='''
  An Apotheosis addon focusing on integration and compatibility
  '''
  displayTest="MATCH_VERSION"

[[dependencies.fallen_gems_affixes]]
  modId="apotheosis"
  mandatory=true
  versionRange="[1.0,)"
  ordering="AFTER"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
  modId="additional_attributes"
  mandatory=true
  versionRange="[1.1.0,)"
  ordering="AFTER"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
  modId="runiclib"
  mandatory=true
  versionRange="[4,)"
  ordering="AFTER"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
  modId="forge"
  mandatory=true
  versionRange= "[47.4.0,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1,1.20.2)"
  ordering="NONE"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
  modId="irons_spellbooks"
  mandatory=false
  versionRange="[1.0,)"
  ordering="AFTER"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
  modId="apothluckaffix"
  mandatory=false
  versionRange="[1.0,)"
  ordering="AFTER"
  side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="cataclysm"
mandatory=false
versionRange="[2.0,)"
ordering="AFTER"
side="BOTH"
