modLoader="javafml"

loaderVersion="${loader_version_range}"

license="LGPL-2.1-or-later"
issueTrackerURL=""

[[mods]]
modId="fallen_gems_affixes"
version="1.0.0"
displayName="Fallen Gems Affixes"
displayURL="https://github.com/KiraKayn/Fallen-Gems-Affixes"
credits="me"
authors="Kayn, Rtxyd"
description=''' An Apotheosis addon focusing on integration and compatibility'''

[[mixins]]
config="fallen_gems_affixes.mixins.json"

[[dependencies.fallen_gems_affixes]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="additional_attributes"
type="required"
versionRange="[1.2.2,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="cataclysm_spellbooks"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="cataclysm"
type="optional"
versionRange="[2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="irons_spellbooks"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="apotheosis"
type="required"
versionRange="[8.3.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="patchouli"
type="required"
versionRange="[1.21-88,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="attributefix"
type="optional"
versionRange="[21.1.2,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.fallen_gems_affixes]]
modId="prickle"
type="optional"
versionRange="[21.1.8,)"
ordering="AFTER"
side="BOTH"